// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKgvOiFPvDWH0xwhODzpTZRvW-KEc0BMo',
    appId: '1:821626913913:web:fba1f2ed6dbe45fcdc00a8',
    messagingSenderId: '821626913913',
    projectId: 'recruiterly-e3543',
    authDomain: 'recruiterly-e3543.firebaseapp.com',
    storageBucket: 'recruiterly-e3543.firebasestorage.app',
    measurementId: 'G-1HFWNPQ3QD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9JzNE_WVy0CoqERZ8rS31epGm_nZ0J58',
    appId: '1:821626913913:android:1fc2f10e0172ef64dc00a8',
    messagingSenderId: '821626913913',
    projectId: 'recruiterly-e3543',
    storageBucket: 'recruiterly-e3543.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs28t1XuxN2NkbA9duGLkJiQkwxG7BPHw',
    appId: '1:821626913913:ios:ae2c1ec6f2a9b0c6dc00a8',
    messagingSenderId: '821626913913',
    projectId: 'recruiterly-e3543',
    storageBucket: 'recruiterly-e3543.firebasestorage.app',
    iosBundleId: 'com.example.recruiterly',
  );
}
